### PR TITLE
Restore previous rocm_install_targets behavior on Windows

### PR DESCRIPTION
**Pull request by apwojcik**
On Windows, we need to behave the old way when installing build artifacts—binaries, CMake configs, and development files.

### CODE REVIEW

**Review by ahsan-ca — APPROVED** [review]

**Review by cgmb — APPROVED** [review]
I approve on the condition that you explain what it is about the current behaviour that causes problems on Windows.

**Comment by apwojcik** [comment]
> I approve on the condition that you explain what it is about the current behaviour that causes problems on Windows.

The problem is in the fixed DLL search order. Please read more here: https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order
On Windows, all DLLs must be in an application's runtime directory unless loaded at runtime by the full path. 

Each dynamically linked DLL is subject to the DLL search order procedure. There is no RPATH on Windows.

**Comment by eidenyoshida** [comment]
@apwojcik is this change still required? If so can you update the branch and re-assess for merge. Thanks

**Comment by apwojcik** [comment]
> @apwojcik is this change still required? If so can you update the branch and re-assess for merge. Thanks

Yes, this is required. I thought the PR was already merged!

**Pull request merged**
