### PR TITLE
Add `--config` option for clang version < 14

### PR DESCRIPTION
**Pull request by umangyadav**
`--config-file` option is only available for `clang v14++`. 

https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/index.html

For versions < 14, need to use `--config` 

https://releases.llvm.org/13.0.0/tools/clang/tools/extra/docs/clang-tidy/index.html

### CODE REVIEW

**Review by pfultz2 — APPROVED** [review]

**Comment by umangyadav** [comment]
Hold on from merging this :

For some reason `--config` option is not parsing `.clang-tidy` file correctly for MIGraphX.

**Comment by pfultz2** [comment]
> In github actions it uses clang v11.

It uses the clang-tidy from rocm. Where are you seeing it using clang v11?

**Comment by pfultz2** [comment]
> GH actions wouldn't have ROCm installed.
> 
> https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/actions/runs/4690184294/jobs/8312941796?pr=1680

We dont run clang-tidy in those jobs. The job that runs clang tidy has rocm installed in the docker container.

**Comment by eidenyoshida** [comment]
@umangyadav wondering if this is still an issue or if this PR can be closed? thanks

**Comment by umangyadav** [comment]
> @umangyadav wondering if this is still an issue or if this PR can be closed? thanks

Closing this ticket for now. I can reopen if necessary.

**Pull request closed without merging**
